# Program name: move_safe_singlepoint.py

import numpy as np
import cv2
import roboticstoolbox as rtb
from spatialmath import SE3
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('TkAgg') # Or 'Qt5Agg' if you have the system Qt installed
import pyzed.sl as sl
from move_xyz_safe import UR5eSafeController

def detect_tennis_ball_center(hsv_image):
    #custom HSV bounds for the neon tennis ball
    lower = np.array([25, 70, 90])
    upper = np.array([45, 255, 255])
    mask = cv2.inRange(hsv_image, lower, upper)

    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if contours:
        largest = max(contours, key=cv2.contourArea)
        M = cv2.moments(largest)
        if M['m00'] != 0:
            cx = int(M['m10'] / M['m00'])
            cy = int(M['m01'] / M['m00'])
            return cx, cy, largest
    return None, None, None

def get_live_ball_camera_coords():
    """Initializes ZED, takes a single photo, and returns ball XYZ in Camera Frame."""
    zed = sl.Camera()
    init_params = sl.InitParameters()
    init_params.depth_mode = sl.DEPTH_MODE.NEURAL
    init_params.coordinate_units = sl.UNIT.METER
    
    if zed.open(init_params) != sl.ERROR_CODE.SUCCESS:
        print("[ERROR] Failed to open ZED camera.")
        return None

    image_zed = sl.Mat()
    point_cloud = sl.Mat()
    runtime_params = sl.RuntimeParameters()
    ball_cam_xyz = None

    print("[INFO] Capturing live photo for ball detection...")
    # Grab a fresh frame
    if zed.grab(runtime_params) == sl.ERROR_CODE.SUCCESS:
        zed.retrieve_image(image_zed, sl.VIEW.LEFT)
        zed.retrieve_measure(point_cloud, sl.MEASURE.XYZ)
        
        frame = image_zed.get_data()
        hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
        cx, cy, _ = detect_tennis_ball_center(hsv)

        if cx is not None:
            err, point = point_cloud.get_value(cx, cy)
            if err == sl.ERROR_CODE.SUCCESS and not np.isnan(point[2]):
                ball_cam_xyz = np.array([point[0], point[1], point[2], 1.0])
                # Show detection for 2 seconds to confirm
                cv2.circle(frame, (cx, cy), 10, (0, 0, 255), -1)
                cv2.imshow("Live Detection Confirmation", frame)
                cv2.waitKey(2000)
                cv2.destroyAllWindows()

    zed.close()
    return ball_cam_xyz

def autonomous_ball_reach(pitch_deg=180):
    # 1. Initialize Controller (Handles 45-deg tilt and DH params)
    ctrl = UR5eSafeController(ip="192.168.5.4")
    
    try:
        # 1. Get Live Ball Data
        ball_local = get_live_ball_camera_coords()
        if ball_local is None:
            print("[ABORT] Ball not detected.")
            return

        # 2. Transform Camera Frame to World Frame
        # Matrix generated by detect_tennisball_Calibration.py
        T_cam_to_robot = np.load("cam_to_robot_transform.npy")
        ball_world = T_cam_to_robot @ ball_local
        tx, ty, tz = ball_world[:3]
        
        # If the gripper is open, you might want to stop slightly higher or lower.
        # This adds 0.015m (1.5cm) to the Z-axis in the World Frame.
        gripper_z_offset = 0.0
        tz = tz - gripper_z_offset
        
        print(f"\n[TARGET] Ball at World XYZ: {tx:.3f}, {ty:.3f}, {tz:.3f}")

        # 3. Solve for IK with angled approach
        q_start = ctrl.rtde_r.getActualQ()
        pitch_rad = np.deg2rad(pitch_deg)
        
        # Define target pose with user-defined approach angle
        T_target = SE3(tx, ty, tz) * SE3.RPY(0, pitch_rad, 0)
        
        T_base_target = ctrl.robot.base.inv() * T_target
        
        print(f"\n[FRAME VERIFICATION]")
        print(f"World Frame Target (Table/Camera): {T_target.t}")
        print(f"Base Frame Target (Robot Motors):  {T_base_target.t}")
        print(f"Base Offset Applied: {ctrl.robot.base.t}")
        
        # Calculate distance and angles in World Frame
        dist = np.sqrt(tx**2 + ty**2 + tz**2)
        azimuth = np.degrees(np.arctan2(ty, tx))
        elevation = np.degrees(np.arcsin(tz / dist))
        
        print(f"\n[OBJECT TARGET]")
        print(f"Distance: {dist:.3f} m")
        print(f"Horizontal Angle: {azimuth:.2f}°")
        print(f"Pos. Vertical Angle: {elevation:.2f}°")
        
        # Weighted mask to allow tilt flexibility
        W = np.array([1.0, 1.0, 1.0, 0, 0, 0])
        sol = ctrl.robot.ikine_LM(T_target, q0=q_start, mask=W)

        if not sol.success:
            print("[ABORT] Target unreachable.")
            return

        # --- 4. Custom Visualization (Black vs Blue) ---
        actual_poses = ctrl.robot.fkine_all(q_start)
        target_poses = ctrl.robot.fkine_all(sol.q)
        actual_coords = np.array([p.t for p in actual_poses])
        target_coords = np.array([p.t for p in target_poses])

        fig = plt.figure(figsize=(10, 8))
        ax = fig.add_subplot(111, projection='3d')
        ax.plot(actual_coords[:,0], actual_coords[:,1], actual_coords[:,2], 'k-o', label='Actual (Black)')
        ax.plot(target_coords[:,0], target_coords[:,1], target_coords[:,2], 'b-o', label='Target (Blue)')
        ax.scatter(tx, ty, tz, color='lawngreen', s=100, label='Tennis Ball')
        ax.set_title("Movement Preview (Tilted Base 45°)")
        ax.legend()
        ax.view_init(elev=25, azim=45)
        plt.show()

        # 5. Execute Movement
        confirm = input(f"Move arm to tennis ball at ({tx:.3f}, {ty:.3f}, {tz:.3f})? (y/n): ")
        if confirm.lower() == 'y':
            ctrl.rtde_c.moveJ(sol.q, 0.25, 1.0)
            print("[STATUS] Target reached.")
            if input("Return to start? (y/n): ").lower() == 'y':
                ctrl.rtde_c.moveJ(q_start, 0.25, 1.0)
        else:
            print("[ABORT] Cancelled.")

    except Exception as e:
        print(f"[ERROR] Logic Failure: {e}")
    finally:
        ctrl.cleanup()

if __name__ == "__main__":
    autonomous_ball_reach(pitch_deg=180)
